#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations users blocks bot lms quiz results services social tags users
python manage.py migrate
python manage.py collectstatic --noinput
python manage.py runserver 0.0.0.0:80
