# versio of docker-compose file format
# https://docs.docker.com/compose/compose-file/
version: '3'

services:
  # service for database
  db:
    image: postgres

  # service for python with django
  web:
    # path to Dockerfile
    build:
      # starting path for all commands inside Dockerfile
      context: .
      dockerfile: docker/Dockerfile.web
    # default command  
    command: python3 manage.py runserver 0.0.0.0:8000
    # mount all volumes to the code directory
    volumes:
      - ./django/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db